# INTRUCCIONES PARA VER LOS DATOS en el container Postgress :)
# Despues de haber añadido profesores desde Swagger de FastAPI 

# docker exec -it db psql -U postgres
# \c guille_db
# select * from profesores;

# Para salir de pgres: \q



services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: guille_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mired

  api:
    image: matope1/api_guille  #Imagen en DockerHub
    container_name: api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@db:5432/guille_db
    networks:
      - mired
    command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000" # Espera 5seg para que se levante antes la BBDD


volumes:
  postgres_data:

networks:
  mired:
    driver: bridge